server:
  port: 1000

dubbo:
  consumer:
    check: false
  registry:
    #挂载到 Spring Cloud 注册中心
    address: spring-cloud://47.93.248.56
  cloud:
    #表示服务的提供方
    subscribed-services: spring-cloud-service-server,spring-cloud-service-server2

spring:
  application:
    name: server1
  main:
    allow-bean-definition-overriding: true
  cloud:
    nacos:
      config:
        server-addr: 47.93.248.56:8848
        file-extension: yaml
        namespace: c1a7a573-39e6-4bd2-9b0c-7da53efba5a3
      discovery:
        server-addr: 47.93.248.56:8848
        namespace: c1a7a573-39e6-4bd2-9b0c-7da53efba5a3
        group: bank
