nacos:
  config:
    server-addr: 47.93.248.56:8848
    namespace: c1a7a573-39e6-4bd2-9b0c-7da53efba5a3
    data-id: server1
    group: DEFAULT_GROUP
    username: nacos
    password: nacos
    auto-refresh: true
    bootstrap:
      enable: true
    type: yaml
  discovery:
    server-addr: 47.93.248.56:8848
    namespace: c1a7a573-39e6-4bd2-9b0c-7da53efba5a3
    username: nacos
    password: nacos
    auto-register: true
    register:
      enabled: true

spring:
  application:
    name: ssss